In [27]:
from function import Matrix
import numpy as np

A = np.array([[4, 3, 2],
              [1, 2, 3],
              [2, 1, 4]])

print("Original Matrix:")
print(A)
print("\n" + "="*50 + "\n")
Mat=Matrix(A)


Original Matrix:
[[4 3 2]
 [1 2 3]
 [2 1 4]]




In [28]:
print("RREF:")
print(Mat.rref())
print("\n" + "="*50 + "\n")

RREF:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




In [29]:
print("Determinant:")
print(Mat.determinant())
print("\n" + "="*50 + "\n")

Determinant:
20.0




In [30]:
print("Inverse:")
print(Mat.inverse())
print("\n" + "="*50 + "\n")

Inverse:
[[ 0.25 -0.5   0.25]
 [ 0.1   0.6  -0.5 ]
 [-0.15  0.1   0.25]]




In [32]:
L, U = Mat.lu_decomposition()
print("LU Decomposition:")
print("L:")
print(L)
print("\nU:")
print(U)
print("\n" + "="*50 + "\n")

LU Decomposition:
L:
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

U:
[[4.   3.   2.  ]
 [0.   1.25 2.5 ]
 [0.   0.   4.  ]]




In [ ]:
V = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]]).T

print("Gram-Schmidt:")
print("Original vectors (columns):")
print(V)
print("\nOrthonormal vectors:")
print(Mat.gram_schmidt(V))

Gram-Schmidt:
Original vectors (columns):
[[1 1 0]
 [1 0 1]
 [0 1 1]]

Orthonormal vectors:


TypeError: Matrix.gram_schmidt() takes 1 positional argument but 2 were given