In [13]:
from function import rref,gram_schmidt,lu_decomposition,inverse,determinant
import numpy as np

A = np.array([[4, 3, 2],
              [1, 2, 3],
              [2, 1, 4]])

print("Original Matrix:")
print(A)
print("\n" + "="*50 + "\n")



Original Matrix:
[[4 3 2]
 [1 2 3]
 [2 1 4]]




In [14]:
print("RREF:")
print(rref(A))
print("\n" + "="*50 + "\n")

RREF:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




In [15]:
print("Determinant:")
print(determinant(A))
print("\n" + "="*50 + "\n")

Determinant:
20.0




In [16]:
print("Inverse:")
print(inverse(A))
print("\n" + "="*50 + "\n")

Inverse:
[[ 0.25 -0.5   0.25]
 [ 0.1   0.6  -0.5 ]
 [-0.15  0.1   0.25]]




In [17]:
L, U = lu_decomposition(A)
print("LU Decomposition:")
print("L:")
print(L)
print("\nU:")
print(U)
print("\n" + "="*50 + "\n")

LU Decomposition:
L:
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

U:
[[4.   3.   2.  ]
 [0.   1.25 2.5 ]
 [0.   0.   4.  ]]




In [18]:
V = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]]).T

print("Gram-Schmidt:")
print("Original vectors (columns):")
print(V)
print("\nOrthonormal vectors:")
print(gram_schmidt(V))

Gram-Schmidt:
Original vectors (columns):
[[1 1 0]
 [1 0 1]
 [0 1 1]]

Orthonormal vectors:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
